---
- hosts: all
  become: yes
  become_user: deploy
  tasks:
    - name: Clone app repos
      command: git -C /home/deploy clone git@{{ item }}.github.com:{{ github_account }}/{{ item }}.git
      args:
        creates: /home/deploy/{{ item }}/
      loop: "{{ apps }}"
      
    # .envrc will be sourced by the deploy script to set environment variables
    - name: Copy environment variable files
      copy:
        src: ./{{ item }}-envrc
        dest: /home/deploy/{{ item }}/.envrc
      loop: "{{ apps }}"
